---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - ruby-rubygems
      - ruby-dev
      - dirsearch
      - curl
      - vim-gtk3
      - ufw
      - rsyslog
      - burpsuite
      - dconf-cli
      - openjdk-17-jdk
      - golang
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - sqlitebrowser
      - xxd
      - xclip
      - hashcat
      - john
      - nmap
      - freerdp3-x11
      - ldap-utils
    state: latest
  become: true
  become_method: sudo
