---
- name: "Use debian-stable version"
  shell: "echo \"deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable\" | tee /etc/apt/sources.list.d/docker.list"
  become: true
  become_method: sudo

- name: "Import gpg key"
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  become: true
  become_method: sudo

- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Update repo"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Docker"
  shell: |
    apt install docker-ce docker-ce-cli containerd.io -y
  become: true
  become_method: sudo

- name: "Setting user on docker group"
  user:
    name: "{{ ansible_user_id }}"  # Use the current user
    groups: docker
    append: yes
  become: true
  become_method: sudo
