---
- name: "Installing tools from Gems"
  command: "gem install {{ item }}"
  with_items:
    - logger
    - stringio
    - winrm
    - builder
    - erubi
    - gssapi
    - gyoku
    - httpclient
    - logging
    - little-plugger
    - nori
    - rubyntlm
    - winrm-fs
    - evil-winrm
  become: true
  become_method: sudo

