---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'bloodyAD', url: 'git+https://github.com/CravateRouge/bloodyAD.git' }
    - { name: 'bloodhound-python', url: 'git+https://github.com/dirkjanm/BloodHound.py.git' }
- name: "Ensuring pip path"
  shell: 
    cmd: "pipx ensurepath"
  args:
    executable: /bin/zsh
