---
- name: Clone the Kali clean repository
  git:
    repo: "https://github.com/xct/kali-clean"
    dest: "/opt/kali-clean"
  become: true
  become_method: sudo

- name: Run the installation script
  command: "./install.sh"
  args:
    chdir: "/opt/kali-clean"

